### ISSUE TITLE
Do not call callback with error when changes are detected

### ISSUE THREAD

**Issue by remorses** [jihchi/dify-bin#3]
Currently if files have changes detected the callback will be called with the error `Error: Command failed: ...`

It would be better to not fail when there are changes, if you still want to return non 0 code on the rust `dify` cli then you could return a special error code like `90` and in `dify-bin` check  `error.exitCode`  to call the callback without error

I can open a PR if you agree

**Comment by jihchi** [comment]
Could you please provide a re-producible example?

I'm unable to reproduce the same error as you mentioned, please see [here](https://github.com/jihchi/dify-bin/pull/4/files#diff-11f05288579cea8d71edae2a6cf81458e0ef5c0d5f44922afccbd96ee5c21ca4R7-R25).

**Comment by remorses** [comment]
Sorry, i was a bit tired yesterday and framed the issue incorrectly

I opened another issue #5
